### PR TITLE
fix: do not break images for already sent emails on update

### PR DESCRIPTION
**Pull request by wa0x6e**
Add back old images. These were used in previous templates version, and deleting them from the server were breaking image hotlink in already sent emails

### CODE REVIEW

**Comment by bonustrack** [comment]
We dont need these image if next email will not break

**Comment by wa0x6e** [comment]
Old images removed, existing image has been renamed to include a checksum, to make it obvious it should not be edited

**Comment by wa0x6e** [comment]
Images are now base64

**Review by Todmy — APPROVED** [review]
utACK

**Pull request merged**
