### PR TITLE
style: update and locally host snapshot logo

### PR DESCRIPTION
**Pull request by wa0x6e**
This PR:

- Update the snapshot logo by another one including the snapshot name
- Locally host the logo on the same app, instead of hotlinking from external source

This PR is also adding another variable in .env, for the project hostname, and allow using absolute link anywhere on the templates, without depending on express request.

### CODE REVIEW

**Comment by wa0x6e** [comment]
With a fixed size logo:
Screenshot 2023-03-19 at 11 28 16 PM
Screenshot 2023-03-19 at 11 29 12 PM


With a dynamic size logo, logo seems a little too big
Screenshot 2023-03-19 at 11 29 41 PM

**Review by bonustrack — APPROVED** [review]
utACK

**Comment by bonustrack** [comment]
We should always use "Sentence case" and not "Title Case"

**Comment by bonustrack** [comment]
Also sentences should end with a `.`

**Pull request merged**
