### PR TITLE
feat: add unsubscribe link to email

### LINKED ISSUE #1: feat: add unsubscribe link to email
The server should have an Ethereum private key, the unsubscribe link should include a code which is generated with a signature of an EIP712 message that include the email to unsubscribe

### PR DESCRIPTION
**Pull request by wa0x6e**
Fixes #1

This PR add an unsubscribe link to summary email footers.

This link redirect to the envelop-ui, and wait for this later to trigger a POST request with the provided query params to initiate the unsubscribe method.

This PR is based on #25 , and most of the changes are explained in the corresponding ticket

PR should be ready as is, but can be tweaked: 

- On unsubscribe, should we just delete the row, or add a extra `active` column in the table to soft delete, and avoid asking for verification if the user subscribe again ?
- Should we just put a unsubscribe link in the footer, or keep the current message ?

### CODE REVIEW

**Comment by bonustrack** [comment]
> On unsubscribe, should we just delete the row, or add a extra active column in the table to soft delete, and avoid asking for verification if the user subscribe again ?

On unsubscribe we should delete the email from the table

> Should we just put a unsubscribe link in the footer, or keep the current message ?

Not sure I understand the difference here. Ideally we should have unsubscribe to also appear here: 
image

**Comment by bonustrack** [comment]
How to test this PR?

**Comment by wa0x6e** [comment]
There is an unsubscribe link in the email footer

Coupled with envelop-ui, the whole workflow can be tested

I am still wondering why the `unsubscribe` link does not appear in the email top in gmail, maybe it's not automatic

**Review by bonustrack — APPROVED** [review]
tACK

**Pull request merged**
